export const REQUEST_ARTICLES = 'REQUEST_ARTICLES';
export type REQUEST_ARTICLES = typeof REQUEST_ARTICLES;
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';
export type RECEIVE_ARTICLES = typeof RECEIVE_ARTICLES;

export const REQUEST_INFO = 'REQUEST_INFO';
export type REQUEST_INFO = typeof REQUEST_INFO;
export const RECEIVE_INFO = 'RECEIVE_INFO';
export type RECEIVE_INFO = typeof RECEIVE_INFO;


export const REQUEST_ARTICLE = 'REQUEST_ARTICLE';
export type REQUEST_ARTICLE = typeof REQUEST_ARTICLE;
export const RECEIVE_ARTICLE = 'RECEIVE_ARTICLE';
export type RECEIVE_ARTICLE = typeof RECEIVE_ARTICLE;

export const REQUEST_RESUME = 'REQUEST_RESUME';
export type REQUEST_RESUME = typeof REQUEST_RESUME;
export const RECEIVE_RESUME = 'RECEIVE_RESUME';
export type RECEIVE_RESUME = typeof RECEIVE_RESUME;


export  const REQUEST_COLLECT = 'REQUEST_COLLECT';
export type REQUEST_COLLECT = typeof REQUEST_COLLECT;
export const RECEIVE_COLLECT = 'RECEIVE_COLLECT';
export type RECEIVE_COLLECT = typeof RECEIVE_COLLECT;
export const DELETE_COLLECT = 'DELETE_COLLECT';
export type DELETE_COLLECT = typeof DELETE_COLLECT;
export const ADD_COLLECT = 'ADD_COLLECT';
export type ADD_COLLECT = typeof ADD_COLLECT;

export const REQUEST_SAY = 'REQUEST_SAY'
export type REQUEST_SAY = typeof REQUEST_SAY
export const RECEIVE_SAY = 'RECEIVE_SAY'
export type RECEIVE_SAY = typeof RECEIVE_SAY